### ISSUE TITLE
Release on pip

### ISSUE THREAD

**Issue by landerlini** [villoro/html-reports#4]
Dear @villoro,
  html-reports, including the add_figure feature, is now part of the dependencies of a package that we would like to make installable with pip. 
Would it be possible to release on pypi the latest version of html-reports  to ease the dependence resolution step?

Many thanks!

**Comment by villoro** [comment]
I just released the `0.2.0` version on pypi: https://pypi.org/project/html-reports/#history

Have a good day 😀
